/*
 * (c) XTK Devs 2013
 */
var k=!1,v,y=this,aa="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ba=0;function z(a,b){var c=a.split("."),e=y;!(c[0]in e)&&e.execScript&&e.execScript("var "+c[0]);for(var d;c.length&&(d=c.shift());)!c.length&&void 0!==b?e[d]=b:e=e[d]?e[d]:e[d]={}}function H(a,b){function c(){}c.prototype=b.prototype;a.k=b.prototype;a.prototype=new c};var ca=0;z("$",window.i);z("X.release","X2 release 0 2013-02-06 16:34:39 -- http://www.goXTK.com -- @goXTK");z("X.counter",ca);function I(a,b,c){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0;this.a=void 0!==c?c:0}I.prototype.c=function(){return new I(this.x,this.y,this.a)};function J(a,b,c){this.x=a;this.y=b;this.a=c}H(J,I);v=J.prototype;v.c=function(){return new J(this.x,this.y,this.a)};v.d=function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.a*this.a)};v.scale=function(a){this.x*=a;this.y*=a;this.a*=a;return this};v.g=function(){this.x=-this.x;this.y=-this.y;this.a=-this.a;return this};v.normalize=function(){return this.scale(1/this.d())};v.add=function(a){this.x+=a.x;this.y+=a.y;this.a+=a.a;return this};
v.h=function(a){this.x-=a.x;this.y-=a.y;this.a-=a.a;return this};z("X.Vector",J);z("X.Vector.prototype.clone",J.prototype.c);z("X.Vector.prototype.magnitude",J.prototype.d);z("X.Vector.prototype.scale",J.prototype.scale);z("X.Vector.prototype.invert",J.prototype.g);z("X.Vector.prototype.normalize",J.prototype.normalize);z("X.Vector.prototype.add",J.prototype.add);z("X.Vector.prototype.subtract",J.prototype.h);z("X.Vector.dot",function(a,b){return a.x*b.x+a.y*b.y+a.a*b.a});
z("X.Vector.cross",function(a,b){return new J(a.y*b.a-a.a*b.y,a.a*b.x-a.x*b.a,a.x*b.y-a.y*b.x)});z("X.Vector.distance",function(a,b){var c=a.x-b.x,e=a.y-b.y,d=a.a-b.a;return Math.sqrt(c*c+e*e+d*d)});z("X.Vector.lerp",function(a,b,c){return new J(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y),a.a+c*(b.a-a.a))});function K(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}K.prototype.BYTES_PER_ELEMENT=8;K.prototype.set=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};K.prototype.toString=Array.prototype.join;if("undefined"==typeof Float64Array){try{K.BYTES_PER_ELEMENT=8}catch(da){}K.prototype.BYTES_PER_ELEMENT=K.prototype.BYTES_PER_ELEMENT;K.prototype.set=K.prototype.set;K.prototype.toString=K.prototype.toString;z("Float64Array",K)};function L(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}L.prototype.BYTES_PER_ELEMENT=4;L.prototype.set=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};L.prototype.toString=Array.prototype.join;"undefined"==typeof Float32Array&&(L.BYTES_PER_ELEMENT=4,L.prototype.BYTES_PER_ELEMENT=L.prototype.BYTES_PER_ELEMENT,L.prototype.set=L.prototype.set,L.prototype.toString=L.prototype.toString,z("Float32Array",L));function ea(a,b){var c=a[0],e=a[1],d=a[2],c=1/Math.sqrt(c*c+e*e+d*d);b[0]=a[0]*c;b[1]=a[1]*c;b[2]=a[2]*c}function fa(a,b,c){var e=a[0],d=a[1];a=a[2];var f=b[0],j=b[1];b=b[2];c[0]=d*b-a*j;c[1]=a*f-e*b;c[2]=e*j-d*f};function Q(a,b,c,e,d,f,j,l,m,n,g,h,q,r,s,t,w){a[0]=b;a[1]=c;a[2]=e;a[3]=d;a[4]=f;a[5]=j;a[6]=l;a[7]=m;a[8]=n;a[9]=g;a[10]=h;a[11]=q;a[12]=r;a[13]=s;a[14]=t;a[15]=w;return a}function ga(a,b,c){a[b]=c[0];a[b+4]=c[1];a[b+8]=c[2];a[b+12]=c[3]}function ha(a,b,c,e){var d=a[1]*b+a[5]*c+a[9]*e+a[13],f=a[2]*b+a[6]*c+a[10]*e+a[14],j=a[3]*b+a[7]*c+a[11]*e+a[15];a[12]=a[0]*b+a[4]*c+a[8]*e+a[12];a[13]=d;a[14]=f;a[15]=j;return a}new Float64Array(3);new Float64Array(3);
var ia=[new Float64Array(4),new Float64Array(4),new Float64Array(4)];new Float64Array(16);z("X.Matrix.identity",function(){var a=new Float32Array(16);a[0]=a[5]=a[10]=a[15]=1;return a});z("X.Matrix.clone",function(a){var b=new Float32Array(16);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b});
z("X.Matrix.transpose",function(a,b){if(b==a){var c=a[1],e=a[2],d=a[3],f=a[6],j=a[7],l=a[11];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=c;b[6]=a[9];b[7]=a[13];b[8]=e;b[9]=f;b[11]=a[14];b[12]=d;b[13]=j;b[14]=l}else b[0]=a[0],b[1]=a[4],b[2]=a[8],b[3]=a[12],b[4]=a[1],b[5]=a[5],b[6]=a[9],b[7]=a[13],b[8]=a[2],b[9]=a[6],b[10]=a[10],b[11]=a[14],b[12]=a[3],b[13]=a[7],b[14]=a[11],b[15]=a[15];return b});
z("X.Matrix.determinant",function(a){var b=a[0],c=a[1],e=a[2],d=a[3],f=a[4],j=a[5],l=a[6],m=a[7],n=a[8],g=a[9],h=a[10],q=a[11],r=a[12],s=a[13],t=a[14];a=a[15];return(b*j-c*f)*(h*a-q*t)-(b*l-e*f)*(g*a-q*s)+(b*m-d*f)*(g*t-h*s)+(c*l-e*j)*(n*a-q*r)-(c*m-d*j)*(n*t-h*r)+(e*m-d*l)*(n*s-g*r)});
z("X.Matrix.invert",function(a,b){var c=a[0],e=a[1],d=a[2],f=a[3],j=a[4],l=a[5],m=a[6],n=a[7],g=a[8],h=a[9],q=a[10],r=a[11],s=a[12],t=a[13],w=a[14],A=a[15],x=c*l-e*j,u=c*m-d*j,B=c*n-f*j,C=e*m-d*l,D=e*n-f*l,E=d*n-f*m,F=g*t-h*s,G=g*w-q*s,M=g*A-r*s,N=h*w-q*t,O=h*A-r*t,P=q*A-r*w,p=x*P-u*O+B*N+C*M-D*G+E*F;if(0==p)return k;p=1/p;b[0]=(l*P-m*O+n*N)*p;b[1]=(-e*P+d*O-f*N)*p;b[2]=(t*E-w*D+A*C)*p;b[3]=(-h*E+q*D-r*C)*p;b[4]=(-j*P+m*M-n*G)*p;b[5]=(c*P-d*M+f*G)*p;b[6]=(-s*E+w*B-A*u)*p;b[7]=(g*E-q*B+r*u)*p;b[8]=
(j*O-l*M+n*F)*p;b[9]=(-c*O+e*M-f*F)*p;b[10]=(s*D-t*B+A*x)*p;b[11]=(-g*D+h*B-r*x)*p;b[12]=(-j*N+l*G-m*F)*p;b[13]=(c*N-e*G+d*F)*p;b[14]=(-s*C+t*u-w*x)*p;b[15]=(g*C-h*u+q*x)*p;return!0});z("X.Matrix.multVec3",function(a,b,c){var e=b[0],d=b[1];b=b[2];c[0]=e*a[0]+d*a[4]+b*a[8]+a[12];c[1]=e*a[1]+d*a[5]+b*a[9]+a[13];c[2]=e*a[2]+d*a[6]+b*a[10]+a[14];return c});
z("X.Matrix.makePerspective",function(a,b,c,e,d){var f=b/2;b=d-e;var j=Math.sin(f);if(0==b||0==j||0==c)return a;f=Math.cos(f)/j;return Q(a,f/c,0,0,0,0,f,0,0,0,0,-(d+e)/b,-1,0,0,-(2*e*d)/b,0)});z("X.Matrix.makeFrustum",function(a,b,c,e,d,f,j){return Q(a,2*f/(c-b),0,0,0,0,2*f/(d-e),0,0,(c+b)/(c-b),(d+e)/(d-e),-(j+f)/(j-f),-1,0,0,-(2*j*f)/(j-f),0)});z("X.Matrix.makeOrtho",function(a,b,c,e,d,f,j){return Q(a,2/(c-b),0,0,0,0,2/(d-e),0,0,0,0,-2/(j-f),0,-(c+b)/(c-b),-(d+e)/(d-e),-(j+f)/(j-f),1)});
z("X.Matrix.makeLookAt",function(a,b,c,e){var d=ia[0];d[0]=c[0]-b[0];d[1]=c[1]-b[1];d[2]=c[2]-b[2];ea(d,d);d[3]=0;c=ia[1];fa(d,e,c);ea(c,c);c[3]=0;e=ia[2];fa(c,d,e);ea(e,e);e[3]=0;d[0]=-d[0];d[1]=-d[1];d[2]=-d[2];ga(a,0,c);ga(a,1,e);ga(a,2,d);a[3]=0;a[7]=0;a[11]=0;a[15]=1;ha(a,-b[0],-b[1],-b[2]);return a});z("X.Matrix.translate",ha);z("X.Matrix.scale",function(a,b,c,e){return Q(a,a[0]*b,a[1]*b,a[2]*b,a[3]*b,a[4]*c,a[5]*c,a[6]*c,a[7]*c,a[8]*e,a[9]*e,a[10]*e,a[11]*e,a[12],a[13],a[14],a[15])});
z("X.Matrix.rotate",function(a,b,c,e,d){var f=a[0],j=a[1],l=a[2],m=a[3],n=a[4],g=a[5],h=a[6],q=a[7],r=a[8],s=a[9],t=a[10],w=a[11],A=Math.cos(b),x=Math.sin(b),u=1-A;b=c*c*u+A;var B=c*e*u+d*x,C=c*d*u-e*x,D=c*e*u-d*x,E=e*e*u+A,F=e*d*u+c*x,G=c*d*u+e*x;c=e*d*u-c*x;d=d*d*u+A;return Q(a,f*b+n*B+r*C,j*b+g*B+s*C,l*b+h*B+t*C,m*b+q*B+w*C,f*D+n*E+r*F,j*D+g*E+s*F,l*D+h*E+t*F,m*D+q*E+w*F,f*G+n*c+r*d,j*G+g*c+s*d,l*G+h*c+t*d,m*G+q*c+w*d,a[12],a[13],a[14],a[15])});
z("X.Matrix.rotateX",function(a,b){var c=a[4],e=a[5],d=a[6],f=a[7],j=a[8],l=a[9],m=a[10],n=a[11],g=Math.cos(b),h=Math.sin(b);a[4]=c*g+j*h;a[5]=e*g+l*h;a[6]=d*g+m*h;a[7]=f*g+n*h;a[8]=c*-h+j*g;a[9]=e*-h+l*g;a[10]=d*-h+m*g;a[11]=f*-h+n*g;return a});z("X.Matrix.rotateY",function(a,b){var c=a[0],e=a[1],d=a[2],f=a[3],j=a[8],l=a[9],m=a[10],n=a[11],g=Math.cos(b),h=Math.sin(b);a[0]=c*g+j*-h;a[1]=e*g+l*-h;a[2]=d*g+m*-h;a[3]=f*g+n*-h;a[8]=c*h+j*g;a[9]=e*h+l*g;a[10]=d*h+m*g;a[11]=f*h+n*g;return a});
z("X.Matrix.rotateZ",function(a,b){var c=a[0],e=a[1],d=a[2],f=a[3],j=a[4],l=a[5],m=a[6],n=a[7],g=Math.cos(b),h=Math.sin(b);a[0]=c*g+j*h;a[1]=e*g+l*h;a[2]=d*g+m*h;a[3]=f*g+n*h;a[4]=c*-h+j*g;a[5]=e*-h+l*g;a[6]=d*-h+m*g;a[7]=f*-h+n*g;return a});function ja(){0!=ka&&(this.j=Error().stack,this[aa]||(this[aa]=++ba))}var ka=0;var R,la,S,ma;function na(){return y.navigator?y.navigator.userAgent:null}ma=S=la=R=k;var T;if(T=na()){var oa=y.navigator;R=0==T.indexOf("Opera");la=!R&&-1!=T.indexOf("MSIE");S=!R&&-1!=T.indexOf("WebKit");ma=!R&&!S&&"Gecko"==oa.product}var pa=R,U=la,qa=ma,ra=S,sa;
a:{var V="",W;if(pa&&y.opera)var ta=y.opera.version,V="function"==typeof ta?ta():ta;else if(qa?W=/rv\:([^\);]+)(\)|;)/:U?W=/MSIE\s+([^\);]+)(\)|;)/:ra&&(W=/WebKit\/(\S+)/),W)var ua=W.exec(na()),V=ua?ua[1]:"";if(U){var va,wa=y.document;va=wa?wa.documentMode:void 0;if(va>parseFloat(V)){sa=String(va);break a}}sa=V}var xa={};
function Y(a){var b;if(!(b=xa[a])){b=0;for(var c=String(sa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=Math.max(c.length,e.length),f=0;0==b&&f<d;f++){var j=c[f]||"",l=e[f]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var g=m.exec(j)||["","",""],h=n.exec(l)||["","",""];if(0==g[0].length&&0==h[0].length)break;b=((0==g[1].length?0:parseInt(g[1],10))<(0==h[1].length?0:parseInt(h[1],10))?-1:(0==g[1].length?0:parseInt(g[1],
10))>(0==h[1].length?0:parseInt(h[1],10))?1:0)||((0==g[2].length)<(0==h[2].length)?-1:(0==g[2].length)>(0==h[2].length)?1:0)||(g[2]<h[2]?-1:g[2]>h[2]?1:0)}while(0==b)}b=xa[a]=0<=b}return b};U&&Y("9");!ra||Y("528");qa&&Y("1.9b")||U&&Y("8")||pa&&Y("9.5")||ra&&Y("528");qa&&!Y("8")||U&&Y("9");Math.floor(2147483648*Math.random()).toString(36);function ya(){ja.call(this)}H(ya,ja);function Z(){ja.call(this);this.e="Base";this.f=ca++;this.b=k}H(Z,ya);Object.defineProperty(Z.prototype,"classname",{get:function(){return this.e}});Object.defineProperty(Z.prototype,"id",{get:function(){return this.f}});Object.defineProperty(Z.prototype,"dirty",{get:function(){return this.b},set:function(a){this.b=a}});z("X.Base",Z);
