/*
 * (c) XTK Devs 2013
 */
var l=!1,F=this,aa="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ba=0;function G(a,b){var c=a.split("."),e=F;!(c[0]in e)&&e.execScript&&e.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&void 0!==b?e[f]=b:e=e[f]?e[f]:e[f]={}}function ca(a,b){function c(){}c.prototype=b.prototype;a.f=b.prototype;a.prototype=new c};var da=0;G("$",window.d);G("X.release","X2 release 0 2013-02-02 13:13:11 -- http://www.goXTK.com -- @goXTK");G("X.counter",da);function L(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}L.prototype.BYTES_PER_ELEMENT=8;L.prototype.set=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};L.prototype.toString=Array.prototype.join;if("undefined"==typeof Float64Array){try{L.BYTES_PER_ELEMENT=8}catch(ea){}L.prototype.BYTES_PER_ELEMENT=L.prototype.BYTES_PER_ELEMENT;L.prototype.set=L.prototype.set;L.prototype.toString=L.prototype.toString;G("Float64Array",L)};function M(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}M.prototype.BYTES_PER_ELEMENT=4;M.prototype.set=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};M.prototype.toString=Array.prototype.join;"undefined"==typeof Float32Array&&(M.BYTES_PER_ELEMENT=4,M.prototype.BYTES_PER_ELEMENT=M.prototype.BYTES_PER_ELEMENT,M.prototype.set=M.prototype.set,M.prototype.toString=M.prototype.toString,G("Float32Array",M));function fa(a,b,c){c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c}function ga(a,b){b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b}function ha(a){var b=a[0],c=a[1];a=a[2];return Math.sqrt(b*b+c*c+a*a)}function N(a,b){var c=1/ha(a);b[0]=a[0]*c;b[1]=a[1]*c;b[2]=a[2]*c;return b}function ia(a,b,c){var e=a[0],f=a[1];a=a[2];var g=b[0],k=b[1];b=b[2];c[0]=f*b-a*k;c[1]=a*g-e*b;c[2]=e*k-f*g;return c};G("X.Vector.create",function(a,b,c){var e=new Float32Array(3);e[0]=a;e[1]=b;e[2]=c;return e});G("X.Vector.clone",function(a){var b=new Float32Array(3);b[0]=a[0];b[1]=a[1];b[2]=a[2];return b});G("X.Vector.add",function(a,b,c){c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c});G("X.Vector.subtract",fa);G("X.Vector.negate",ga);G("X.Vector.scale",function(a,b,c){c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c});G("X.Vector.magnitude",ha);G("X.Vector.normalize",N);
G("X.Vector.dot",function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]});G("X.Vector.cross",ia);G("X.Vector.distance",function(a,b){var c=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2];return Math.sqrt(c*c+e*e+f*f)});G("X.Vector.direction",function(a,b,c){var e=b[0]-a[0],f=b[1]-a[1];a=b[2]-a[2];(b=Math.sqrt(e*e+f*f+a*a))?(b=1/b,c[0]=e*b,c[1]=f*b,c[2]=a*b):c[0]=c[1]=c[2]=0;return c});G("X.Vector.lerp",function(a,b,c,e){var f=a[0],g=a[1];a=a[2];e[0]=(b[0]-f)*c+f;e[1]=(b[1]-g)*c+g;e[2]=(b[2]-a)*c+a;return e});function O(a,b,c,e,f,g,k,m,n,p,h,j,r,s,t,u,w){a[0]=b;a[1]=c;a[2]=e;a[3]=f;a[4]=g;a[5]=k;a[6]=m;a[7]=n;a[8]=p;a[9]=h;a[10]=j;a[11]=r;a[12]=s;a[13]=t;a[14]=u;a[15]=w;return a}function ja(a,b,c){a[b]=c[0];a[b+4]=c[1];a[b+8]=c[2];a[b+12]=c[3]}function ka(a,b,c,e){var f=a[1]*b+a[5]*c+a[9]*e+a[13],g=a[2]*b+a[6]*c+a[10]*e+a[14],k=a[3]*b+a[7]*c+a[11]*e+a[15];a[12]=a[0]*b+a[4]*c+a[8]*e+a[12];a[13]=f;a[14]=g;a[15]=k;return a}new Float64Array(3);new Float64Array(3);
var la=[new Float64Array(4),new Float64Array(4),new Float64Array(4)];new Float64Array(16);G("X.Matrix.identity",function(){var a=new Float32Array(16);a[0]=a[5]=a[10]=a[15]=1;return a});G("X.Matrix.clone",function(a){var b=new Float32Array(16);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b});
G("X.Matrix.transpose",function(a,b){if(b==a){var c=a[1],e=a[2],f=a[3],g=a[6],k=a[7],m=a[11];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=c;b[6]=a[9];b[7]=a[13];b[8]=e;b[9]=g;b[11]=a[14];b[12]=f;b[13]=k;b[14]=m}else b[0]=a[0],b[1]=a[4],b[2]=a[8],b[3]=a[12],b[4]=a[1],b[5]=a[5],b[6]=a[9],b[7]=a[13],b[8]=a[2],b[9]=a[6],b[10]=a[10],b[11]=a[14],b[12]=a[3],b[13]=a[7],b[14]=a[11],b[15]=a[15];return b});
G("X.Matrix.determinant",function(a){var b=a[0],c=a[1],e=a[2],f=a[3],g=a[4],k=a[5],m=a[6],n=a[7],p=a[8],h=a[9],j=a[10],r=a[11],s=a[12],t=a[13],u=a[14];a=a[15];return(b*k-c*g)*(j*a-r*u)-(b*m-e*g)*(h*a-r*t)+(b*n-f*g)*(h*u-j*t)+(c*m-e*k)*(p*a-r*s)-(c*n-f*k)*(p*u-j*s)+(e*n-f*m)*(p*t-h*s)});
G("X.Matrix.invert",function(a,b){var c=a[0],e=a[1],f=a[2],g=a[3],k=a[4],m=a[5],n=a[6],p=a[7],h=a[8],j=a[9],r=a[10],s=a[11],t=a[12],u=a[13],w=a[14],y=a[15],x=c*m-e*k,v=c*n-f*k,z=c*p-g*k,A=e*n-f*m,B=e*p-g*m,C=f*p-g*n,D=h*u-j*t,E=h*w-r*t,H=h*y-s*t,I=j*w-r*u,J=j*y-s*u,K=r*y-s*w,q=x*K-v*J+z*I+A*H-B*E+C*D;if(0==q)return l;q=1/q;b[0]=(m*K-n*J+p*I)*q;b[1]=(-e*K+f*J-g*I)*q;b[2]=(u*C-w*B+y*A)*q;b[3]=(-j*C+r*B-s*A)*q;b[4]=(-k*K+n*H-p*E)*q;b[5]=(c*K-f*H+g*E)*q;b[6]=(-t*C+w*z-y*v)*q;b[7]=(h*C-r*z+s*v)*q;b[8]=
(k*J-m*H+p*D)*q;b[9]=(-c*J+e*H-g*D)*q;b[10]=(t*B-u*z+y*x)*q;b[11]=(-h*B+j*z-s*x)*q;b[12]=(-k*I+m*E-n*D)*q;b[13]=(c*I-e*E+f*D)*q;b[14]=(-t*A+u*v-w*x)*q;b[15]=(h*A-j*v+r*x)*q;return!0});G("X.Matrix.multiplyVector",function(a,b,c){var e=b[0],f=b[1];b=b[2];c[0]=e*a[0]+f*a[4]+b*a[8]+a[12];c[1]=e*a[1]+f*a[5]+b*a[9]+a[13];c[2]=e*a[2]+f*a[6]+b*a[10]+a[14];return c});
G("X.Matrix.multiply",function(a,b,c){var e=a[0],f=a[1],g=a[2],k=a[3],m=a[4],n=a[5],p=a[6],h=a[7],j=a[8],r=a[9],s=a[10],t=a[11],u=a[12],w=a[13],y=a[14];a=a[15];var x=b[0],v=b[1],z=b[2],A=b[3],B=b[4],C=b[5],D=b[6],E=b[7],H=b[8],I=b[9],J=b[10],K=b[11],q=b[12],T=b[13],U=b[14];b=b[15];c[0]=e*x+m*v+j*z+u*A;c[1]=f*x+n*v+r*z+w*A;c[2]=g*x+p*v+s*z+y*A;c[3]=k*x+h*v+t*z+a*A;c[4]=e*B+m*C+j*D+u*E;c[5]=f*B+n*C+r*D+w*E;c[6]=g*B+p*C+s*D+y*E;c[7]=k*B+h*C+t*D+a*E;c[8]=e*H+m*I+j*J+u*K;c[9]=f*H+n*I+r*J+w*K;c[10]=g*H+
p*I+s*J+y*K;c[11]=k*H+h*I+t*J+a*K;c[12]=e*q+m*T+j*U+u*b;c[13]=f*q+n*T+r*U+w*b;c[14]=g*q+p*T+s*U+y*b;c[15]=k*q+h*T+t*U+a*b;return c});G("X.Matrix.perspective",function(a,b,c,e,f){var g=b/2;b=f-e;var k=Math.sin(g);if(0==b||0==k||0==c)return a;g=Math.cos(g)/k;return O(a,g/c,0,0,0,0,g,0,0,0,0,-(f+e)/b,-1,0,0,-(2*e*f)/b,0)});G("X.Matrix.frustum",function(a,b,c,e,f,g,k){return O(a,2*g/(c-b),0,0,0,0,2*g/(f-e),0,0,(c+b)/(c-b),(f+e)/(f-e),-(k+g)/(k-g),-1,0,0,-(2*k*g)/(k-g),0)});
G("X.Matrix.orthographic",function(a,b,c,e,f,g,k){return O(a,2/(c-b),0,0,0,0,2/(f-e),0,0,0,0,-2/(k-g),0,-(c+b)/(c-b),-(f+e)/(f-e),-(k+g)/(k-g),1)});G("X.Matrix.lookAt",function(a,b,c,e){var f=la[0];fa(c,b,f);N(f,f);f[3]=0;c=la[1];ia(f,e,c);N(c,c);c[3]=0;e=la[2];ia(c,f,e);N(e,e);e[3]=0;ga(f,f);ja(a,0,c);ja(a,1,e);ja(a,2,f);a[3]=0;a[7]=0;a[11]=0;a[15]=1;ka(a,-b[0],-b[1],-b[2]);return a});G("X.Matrix.translate",ka);
G("X.Matrix.scale",function(a,b,c,e){return O(a,a[0]*b,a[1]*b,a[2]*b,a[3]*b,a[4]*c,a[5]*c,a[6]*c,a[7]*c,a[8]*e,a[9]*e,a[10]*e,a[11]*e,a[12],a[13],a[14],a[15])});
G("X.Matrix.rotate",function(a,b,c,e,f){var g=a[0],k=a[1],m=a[2],n=a[3],p=a[4],h=a[5],j=a[6],r=a[7],s=a[8],t=a[9],u=a[10],w=a[11],y=Math.cos(b),x=Math.sin(b),v=1-y;b=c*c*v+y;var z=c*e*v+f*x,A=c*f*v-e*x,B=c*e*v-f*x,C=e*e*v+y,D=e*f*v+c*x,E=c*f*v+e*x;c=e*f*v-c*x;f=f*f*v+y;return O(a,g*b+p*z+s*A,k*b+h*z+t*A,m*b+j*z+u*A,n*b+r*z+w*A,g*B+p*C+s*D,k*B+h*C+t*D,m*B+j*C+u*D,n*B+r*C+w*D,g*E+p*c+s*f,k*E+h*c+t*f,m*E+j*c+u*f,n*E+r*c+w*f,a[12],a[13],a[14],a[15])});
G("X.Matrix.rotateX",function(a,b){var c=a[4],e=a[5],f=a[6],g=a[7],k=a[8],m=a[9],n=a[10],p=a[11],h=Math.cos(b),j=Math.sin(b);a[4]=c*h+k*j;a[5]=e*h+m*j;a[6]=f*h+n*j;a[7]=g*h+p*j;a[8]=c*-j+k*h;a[9]=e*-j+m*h;a[10]=f*-j+n*h;a[11]=g*-j+p*h;return a});G("X.Matrix.rotateY",function(a,b){var c=a[0],e=a[1],f=a[2],g=a[3],k=a[8],m=a[9],n=a[10],p=a[11],h=Math.cos(b),j=Math.sin(b);a[0]=c*h+k*-j;a[1]=e*h+m*-j;a[2]=f*h+n*-j;a[3]=g*h+p*-j;a[8]=c*j+k*h;a[9]=e*j+m*h;a[10]=f*j+n*h;a[11]=g*j+p*h;return a});
G("X.Matrix.rotateZ",function(a,b){var c=a[0],e=a[1],f=a[2],g=a[3],k=a[4],m=a[5],n=a[6],p=a[7],h=Math.cos(b),j=Math.sin(b);a[0]=c*h+k*j;a[1]=e*h+m*j;a[2]=f*h+n*j;a[3]=g*h+p*j;a[4]=c*-j+k*h;a[5]=e*-j+m*h;a[6]=f*-j+n*h;a[7]=g*-j+p*h;return a});function ma(){0!=na&&(this.e=Error().stack,this[aa]||(this[aa]=++ba))}var na=0;var P,oa,Q,pa;function qa(){return F.navigator?F.navigator.userAgent:null}pa=Q=oa=P=l;var R;if(R=qa()){var ra=F.navigator;P=0==R.indexOf("Opera");oa=!P&&-1!=R.indexOf("MSIE");Q=!P&&-1!=R.indexOf("WebKit");pa=!P&&!Q&&"Gecko"==ra.product}var sa=P,S=oa,ta=pa,ua=Q,va;
a:{var V="",W;if(sa&&F.opera)var wa=F.opera.version,V="function"==typeof wa?wa():wa;else if(ta?W=/rv\:([^\);]+)(\)|;)/:S?W=/MSIE\s+([^\);]+)(\)|;)/:ua&&(W=/WebKit\/(\S+)/),W)var xa=W.exec(qa()),V=xa?xa[1]:"";if(S){var ya,za=F.document;ya=za?za.documentMode:void 0;if(ya>parseFloat(V)){va=String(ya);break a}}va=V}var Aa={};
function Y(a){var b;if(!(b=Aa[a])){b=0;for(var c=String(va).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,e.length),g=0;0==b&&g<f;g++){var k=c[g]||"",m=e[g]||"",n=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var h=n.exec(k)||["","",""],j=p.exec(m)||["","",""];if(0==h[0].length&&0==j[0].length)break;b=((0==h[1].length?0:parseInt(h[1],10))<(0==j[1].length?0:parseInt(j[1],10))?-1:(0==h[1].length?0:parseInt(h[1],
10))>(0==j[1].length?0:parseInt(j[1],10))?1:0)||((0==h[2].length)<(0==j[2].length)?-1:(0==h[2].length)>(0==j[2].length)?1:0)||(h[2]<j[2]?-1:h[2]>j[2]?1:0)}while(0==b)}b=Aa[a]=0<=b}return b};S&&Y("9");!ua||Y("528");ta&&Y("1.9b")||S&&Y("8")||sa&&Y("9.5")||ua&&Y("528");ta&&!Y("8")||S&&Y("9");Math.floor(2147483648*Math.random()).toString(36);function Ba(){ma.call(this)}ca(Ba,ma);function Z(){ma.call(this);this.b="Base";this.c=da++;this.a=l}ca(Z,Ba);Object.defineProperty(Z.prototype,"classname",{get:function(){return this.b}});Object.defineProperty(Z.prototype,"id",{get:function(){return this.c}});Object.defineProperty(Z.prototype,"dirty",{get:function(){return this.a},set:function(a){this.a=a}});G("X.Base",Z);
